spring.application.name=RoomReservation
spring.datasource.url=jdbc:postgresql://localhost:5432/Room_Reserve_DB
spring.datasource.username=postgres
spring.datasource.password=luan123
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
